import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Link href="/blog">
          <h1>Blogs</h1>
        </Link>
        <Link href="/static-generation">
          <h1>Static Generation</h1>
        </Link>
        <Link href="/static-generation/posts">
          <h1>Posts</h1>
        </Link>
        <Link href="/product">
          <h1>Products</h1>
        </Link>
        <Link href="/news">
          <h1>News</h1>
        </Link>
      </main>
    </>
  );
}
